export const colors = {
  mario: '#ff4026',
  samus: '#353f56',
  kirby: '#fed6e3',
  bowser: '#44745e',
  link: '#1c94c3',
  donkeykong: '#f9da4a',
  fox: '#307cdf',
  falco: '#69b0de',
  marth: '#5da8c8',
  zelda: '#fdeaa4',
  sheik: '#756fd0',
  villager: '#83a88e',
  mewtwo: '#927bc5',
  metaknight: '#5367b0',
  sonic: '#659deb',
  pikachu: '#ffb912',
  iceclimbers: '#a0cafe',
  inkling: '#f02d7d',
  captainfalcon: '#8e8adc',
  zerosuitsamus: '#205ba4',
  wiifittrainer: '#99d481',
  pokemontrainer: '#ffc004',
  ness: '#de413d',
  lucas: '#e06833',
  ryu: '#d0504d',
  ganondorf: '#7974a4',
  ike: '#b64f3e',
  cloud: '#419384',
  snake: '#658198',
  jigglypuff: '#f29bf6',
  pichu: '#dedc1f',
  roy: '#74b65b',
  olimar: '#ccefb0',
  diddykong: '#e05a52',
  lucario: '#b8e3fc',
  lucina: '#7ea6c7',
  robin: '#c387d9',
  bayonetta: '#a5a1e0',
  mrgameandwatch: '#a4a190',
  greninja: '#5673a5',
  drmario: '#e86c6d',
  rob: '#b2b8bd',
  duckhunt: '#8c5d3a',
  pit: '#acdafa',
  darkpit: '#875cbe',
  palutena: '#91e5c1',
  corrin: '#63a7c0',
  bowserjr: '#59bf38',
  toonlink: '#8ce689',
  younglink: '#a5d160',
  kingdedede: '#fce87b',
  rosalinaandluma: '#98d5cd',
  wario: '#fee71f',
  littlemac: '#5d8f72',
  pacman: '#fcb541',
  shulk: '#d5647a',
  wolf: '#cccccc',
  megaman: '#86c1e0',
  luigi: '#5ea444',
  yoshi: '#83cd65',
  piranhaplant: '#00aa82',
  peach: '#f5c9f0',
  daisy: '#f0bb2c',
  kingkrool: '#65873b',
  ridley: '#71456f',
  darksamus: '#3d395e',
  chom: '#b4b4cf',
  byleth: '#282828',
  isabelle: '#c4d37e',
  ken: '#cdd7dc',
  simon: '#76150e',
  richter: '#2a6db0',
  joker: '#b41201',
  hero: '#ccb3f4',
  banjokazooie: '#fcdd76',
  terry: '#355c7d',
  incineroar: '#ffd902',
};

export const names = {
  mario: 'Mario',
  samus: 'Samus',
  kirby: 'Kirby',
  bowser: 'Bowser',
  link: 'Link',
  donkeykong: 'Donkey Kong',
  fox: 'Fox',
  falco: 'Falco',
  marth: 'Marth',
  zelda: 'Zelda',
  sheik: 'Sheik',
  villager: 'Villager',
  mewtwo: 'Mewtwo',
  metaknight: 'Meta Knight',
  sonic: 'Sonic',
  pikachu: 'Pikachu',
  iceclimbers: 'Ice Climbers',
  inkling: 'Inkling',
  captainfalcon: 'Captain Falcon',
  zerosuitsamus: 'Zero Suit Samus',
  wiifittrainer: 'Wii Fit Trainer',
  pokemontrainer: 'Pokémon Trainer',
  ness: 'Ness',
  lucas: 'Lucas',
  ryu: 'Ryu',
  ganondorf: 'Ganondorf',
  ike: 'Ike',
  cloud: 'Cloud',
  snake: 'Snake',
  jigglypuff: 'Jigglypuff',
  pichu: 'Pichu',
  roy: 'Roy',
  olimar: 'Olimar',
  diddykong: 'Diddy Kong',
  lucario: 'Lucario',
  lucina: 'Lucina',
  robin: 'Robin',
  bayonetta: 'Bayonetta',
  mrgameandwatch: 'Pokémon Trainer',
  greninja: 'Greninja',
  drmario: 'Dr. Mario',
  rob: 'Rob',
  duckhunt: 'Duck Hunt',
  pit: 'Pit',
  darkpit: 'Darkpit',
  palutena: 'Palutena',
  corrin: 'Corrin',
  bowserjr: 'Bowser Jr.',
  toonlink: 'Toon Link',
  younglink: 'Young Link',
  kingdedede: 'King Dedede',
  rosalinaandluma: 'Rosalina and Luma',
  wario: 'Wario',
  littlemac: 'Little Mac',
  pacman: 'Pac - Man',
  shulk: 'Shulk',
  wolf: 'Wolf',
  megaman: 'Megaman',
  luigi: 'Luigi',
  yoshi: 'Yoshi',
  piranhaplant: 'Piranha Plant',
  peach: 'Peach',
  daisy: 'Daisy',
  kingkrool: 'King K. Rool',
  ridley: 'Ridley',
  darksamus: 'Dark Samus',
  chom: 'Chrom',
  byleth: 'Byleth',
  isabelle: 'Isabelle',
  ken: 'Ken',
  simon: 'Simon',
  richter: 'Richter',
  joker: 'Joker',
  hero: 'Hero',
  banjokazooie: 'Banjo & Kazooie',
  terry: 'Terry',
  incineroar: 'Incineroar',
};
